apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec: 
  type: LoadBalancer
  selector: #labels arre used as selectors
    app: frontend
    tier: web
    project: expense 
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 8080 #container port number
