apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec: 
  selector: #labels arre used as selectors
    app: backend
    tier: backend
    project: expense 
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #container port number